# Generated by Django 4.2.13 on 2024-06-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attributevalue",
            name="product",
        ),
    ]
