# Generated by Django 4.2.13 on 2024-06-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_attributevalue_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
